### ISSUE TITLE
`realpath` not found on macOS

### ISSUE THREAD

**Issue by matthesjh** [cau-placc/pakcs#1]
When compiling the latest version of `pakcs` on macOS 11.2.1, I get the following error and the installation fails.

```
Try to find SICStus-Prolog...
No SICStus-Prolog found, looking for SWI-Prolog...
scripts/configure-prolog.sh: line 65: realpath: command not found
Cannot find 'sicstus' or 'swipl' executable in path.
Please expand or provide a correct definition for
SICSTUSPROLOG or SWIPROLOG as a parameter for 'make'!
```

The executable `realpath` is not present on macOS by default.

**Comment by mihanus** [comment]
Thanks for the issue. It is interesting, since the man page for `readlink` on Ubuntu/Debian says `Note  realpath(1)  is the preferred command to use for canonicalization functionality.` This was the reason to use `realpath` instead of `readlink -f`. Since the battle between these commands seems undecided but `readlink` seems generally supported (by GNU), I replaced `realpath` by `readlink -f`. This is available in PAKCS 3.4.0b1, or just set `alias readpath="readlink -f"`. Hope this helps.

**Comment by matthesjh** [comment]
Thanks for the quick fix, but I get the following error now:

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

We had this problem already in the past as described [here](https://git.ps.informatik.uni-kiel.de/curry/pakcs/-/issues/19).

**Comment by mihanus** [comment]
Since I do not use macOS: is there a (portable) alternative to obtain the absolute file name?
It seems this is a problem on macOS for a long time, e.g., as discussed [here](https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac).

**Comment by matthesjh** [comment]
Currently, I do not know a suitable alternative. But I ask myself, why the absolute path of the `swipl` executable is needed here. The path is symlinked to `bin/swiprolog`, which is then used during installation. Is there any specific reason why not to use only the result of `which swipl`?

**Comment by mihanus** [comment]
The reason is the change of a symbolic link. For instance, if `/opt/swiprolog` refers to `/usr/lib/swipl-7.6.3` and is later redirected to `/usr/lib/swipl-8.2.3`, then the executables compiled with `/opt/swiprolog/bin/swipl` might become incompatible after this change.

Anyway, I made the script robust against `readlink` errors, i.e., if the call produces an error, it is ignored. I hope this helps.

**Comment by matthesjh** [comment]
Thanks for the latest change, which fixes the problem.
